### ISSUE TITLE
Filter by language?

### ISSUE THREAD

**Issue by BSierakowski** [Taskulu/tweelead#5]
I'm using the Aylien language API to filter the results logged to just the languages that I speak (unfortunately limited to "en" :(. )

Would there be interest in pulling this code in if I submitted a pull request? One issue is that for every tweet that passes the negative sentiment filter we'll make another Aylien API request, exhausting our free 1000 more quickly.

Also, my approach of nesting nested if's is a good sign the code is ready for refactoring :D. 

Let me know if this fits your vision for the repo and I'll submit a pull request (or let you take a stab!)

**Comment by BSierakowski** [comment]
I sent a pull request anyway; feel free to review that and delete this!

**Comment by farhadhf** [comment]
closing
