### ISSUE TITLE
Not writing to the Google Doc sheet

### ISSUE THREAD

**Issue by vikxo** [Taskulu/tweelead#9]
Not writing to the Google Doc sheet- Showing error- Google has officially deprecated ClientLogin. Please upgrade this module and see the readme for more instrucations.

I just cloned the package. What do I need to upgrade? I didnt see any thing in the readme.

**Comment by leonardofed** [comment]
True.

**Comment by farhadhf** [comment]
Hey guys, sorry for the long delay. It's fixed, please clone the new version and follow the instructions in the README file.
